In [61]:
import pandas as pd
A = pd.read_csv('/tmp/a.csv',sep='\t',header=None)

In [62]:
A.columns=['date','user','action']

Last_close=>user,date,date_last_close,next_action
Last_open=>user,date,date_last_open,next_action


user,date,date_last_close,date_last_open

In [67]:
A.action.shift(-1)

0     action2
1       close
2        open
3     action6
4        open
5     action1
6        open
7     action1
8     action2
9        open
10    action1
11    action2
12      close
13    action1
14    action3
15       open
16    action1
17    action2
18       open
19    action1
20    action2
21      close
22    action1
23    action2
24      close
25    action1
26    action2
27    action2
28    action2
29    action4
30        NaN
Name: action, dtype: object

In [68]:
P = pd.merge(A,A,on='user')
L=P[(P.date_x>=P.date_y)].groupby(['user','date_x','action_x'],as_index=(False)).count()
L[((L['action_x']=='open')|( L['action_x']=='close' ))]

Empty DataFrame
Columns: [user, date_x, action_x, date_y, action_y]
Index: []

In [56]:
Open = A.date_x[A.action_x=='open']
Close =A.date_x[A.action_x=='close']

for date in dates:
    o_=max(Open[Open<date])
    
    c_=max(Close[Open<date])
    if c_>o_ or o_ is null:
        op=max(P.dates<c_)

                  date_x  user action_x               date_y action_y
0    2018-02-21 15:53:48    96    close  2018-02-21 15:53:48    close
2    2018-02-21 15:53:48    96    close  2018-02-21 15:51:51     open
6    2018-02-21 15:53:44    96  action2  2018-02-21 15:51:51     open
10   2018-02-21 15:51:51    96     open  2018-02-21 15:51:51     open
14   2018-02-21 15:52:57    96  action6  2018-02-21 15:51:51     open
16   2018-02-21 16:29:22   122    close  2018-02-21 16:29:22    close
17   2018-02-21 16:29:22   122    close  2018-02-21 16:29:19     open
23   2018-02-21 16:29:19   122     open  2018-02-21 16:29:19     open
29   2018-02-21 16:29:20   122  action1  2018-02-21 16:29:19     open
34   2018-02-21 16:50:00   122     open  2018-02-21 16:29:22    close
35   2018-02-21 16:50:00   122     open  2018-02-21 16:29:19     open
37   2018-02-21 16:50:00   122     open  2018-02-21 16:50:00     open
40   2018-02-21 16:50:20   122  action1  2018-02-21 16:29:22    close
41   2018-02-21 16:50:20   122  action1  2018-02-21 16:29:19     open
43   2018-02-21 16:50:20   122  action1  2018-02-21 16:50:00     open
46   2018-02-21 16:50:40   122  action2  2018-02-21 16:29:22    close
47   2018-02-21 16:50:40   122  action2  2018-02-21 16:29:19     open
49   2018-02-21 16:50:40   122  action2  2018-02-21 16:50:00     open
52   2018-02-21 08:00:00   101     open  2018-02-21 08:00:00     open
70   2018-02-21 08:00:30   101  action1  2018-02-21 08:00:00     open
88   2018-02-21 08:01:00   101  action2  2018-02-21 08:00:00     open
106  2018-02-21 08:02:00   101    close  2018-02-21 08:00:00     open
109  2018-02-21 08:02:00   101    close  2018-02-21 08:02:00    close
124  2018-02-21 08:15:00   101  action1  2018-02-21 08:00:00     open
127  2018-02-21 08:15:00   101  action1  2018-02-21 08:02:00    close
142  2018-02-21 08:17:00   101  action3  2018-02-21 08:00:00     open
145  2018-02-21 08:17:00   101  action3  2018-02-21 08:02:00    close
160  2018-02-21 09:00:00   101     open  2018-02-21 08:00:00     open
163  2018-02-21 09:00:00   101     open  2018-02-21 08:02:00    close
166  2018-02-21 09:00:00   101     open  2018-02-21 09:00:00     open
..                   ...   ...      ...                  ...      ...
277  2018-02-21 10:02:00   101    close  2018-02-21 10:00:00     open
280  2018-02-21 10:02:00   101    close  2018-02-21 10:02:00    close
286  2018-02-21 11:00:00   101  action1  2018-02-21 08:00:00     open
289  2018-02-21 11:00:00   101  action1  2018-02-21 08:02:00    close
292  2018-02-21 11:00:00   101  action1  2018-02-21 09:00:00     open
295  2018-02-21 11:00:00   101  action1  2018-02-21 10:00:00     open
298  2018-02-21 11:00:00   101  action1  2018-02-21 10:02:00    close
304  2018-02-21 11:02:15   101  action2  2018-02-21 08:00:00     open
307  2018-02-21 11:02:15   101  action2  2018-02-21 08:02:00    close
310  2018-02-21 11:02:15   101  action2  2018-02-21 09:00:00     open
313  2018-02-21 11:02:15   101  action2  2018-02-21 10:00:00     open
316  2018-02-21 11:02:15   101  action2  2018-02-21 10:02:00    close
322  2018-02-21 11:03:45   101    close  2018-02-21 08:00:00     open
325  2018-02-21 11:03:45   101    close  2018-02-21 08:02:00    close
328  2018-02-21 11:03:45   101    close  2018-02-21 09:00:00     open
331  2018-02-21 11:03:45   101    close  2018-02-21 10:00:00     open
334  2018-02-21 11:03:45   101    close  2018-02-21 10:02:00    close
337  2018-02-21 11:03:45   101    close  2018-02-21 11:03:45    close
340  2018-02-21 12:00:00   101  action1  2018-02-21 08:00:00     open
343  2018-02-21 12:00:00   101  action1  2018-02-21 08:02:00    close
346  2018-02-21 12:00:00   101  action1  2018-02-21 09:00:00     open
349  2018-02-21 12:00:00   101  action1  2018-02-21 10:00:00     open
352  2018-02-21 12:00:00   101  action1  2018-02-21 10:02:00    close
355  2018-02-21 12:00:00   101  action1  2018-02-21 11:03:45    close
358  2018-02-21 12:02:20   101  action2  2018-02-21 08:00:00     open
361  2018-02-21 12:02:20   101  action2  2018-02-21 08:02:00    close
364  2018-02-21 12:02:20   101  action2  2018-02-21 09:00:00     open
367  2018-02-21 12:02:20   101  action2  2018-02-21 10:00:00     open
370  2018-02-21 12:02:20   101  action2  2018-02-21 10:02:00    close
373  2018-02-21 12:02:20   101  action2  2018-02-21 11:03:45    close

[81 rows x 5 columns]